import mongoose,{Model} from 'mongoose';

var productSchema = new mongoose.Schema({
    title:{
        type:String,
        required:true,
        trim:true,
    },
    slug:{
        type:String,
        required:true,
        unique:true,
        lowercase:true,
    },
    description:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Description"
    },
    technicalInfo:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Technical"
    },
    price:
        {
            type:Number,
            required:true,
            default:"0"
        }
    ,
    discount:
        {
            type:Number,
            required:true,
            default:"0"
        }
    ,
    category:{
        type:String,
        required:true,
    },
    brand:{
        type:String,
        required:true,
    },
    quantity:{
        type:Number,
        required:true,
    },
    images:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Image"
    },
    color:[{
        type:String,
        required:true,
    }],
    display:{
        type:Number,
    },
    ram:{
        type:Number,
    },
    storage:{
        type:Number,
    },
    cpu:{
        type:String,
    },
    gpu:{
        type:String,
    },
    resolution:{
        type:String,
    },
    material:{
        type:String,
    },
    ratings:[
        {
            rating:Number,
            name:String,
            date:String,
            comment:String,
            postedby:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"User"
            }
        }
    ],
    totalRating:{
        type:Number,
        default:0
    }
},{
    timestamps:true
})

const Product:Model<any> = mongoose.model("Product",productSchema)

export = Product